export const products = [
  {
    id: 1,
    name: "Enterprise Security Suite",
    category: "Security Products",
    price: 1299.99,
    image: "/images/products/enterprise-security-suite.jpg",
    description:
      "Comprehensive security solution for enterprise networks with advanced threat detection and prevention.",
    features: [
      "Advanced firewall protection",
      "Intrusion detection and prevention",
      "Malware and ransomware protection",
      "24/7 security monitoring",
      "Regular security updates",
    ],
    stock: 15,
    rating: 4.8,
  },
  {
    id: 2,
    name: "Smart Power Manager",
    category: "Power Solutions",
    price: 899.99,
    image: "/images/products/smart-power-manager.jpg",
    description: "Intelligent power management system for optimizing energy consumption in commercial buildings.",
    features: [
      "Real-time power monitoring",
      "Automated load balancing",
      "Energy usage analytics",
      "Remote management via mobile app",
      "Integration with smart building systems",
    ],
    stock: 8,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Network Pro Router",
    category: "Connectivity & Networking",
    price: 349.99,
    image: "/images/products/network-pro-router.jpg",
    description: "High-performance router for business environments with advanced security features.",
    features: [
      "Gigabit Ethernet ports",
      "Dual-band WiFi 6 support",
      "VPN server capabilities",
      "Advanced QoS settings",
      "Guest network isolation",
    ],
    stock: 23,
    rating: 4.9,
  },
  {
    id: 4,
    name: "Cloud Backup Solution",
    category: "IT Products & Services",
    price: 199.99,
    image: "/images/products/cloud-backup.jpg",
    description: "Secure cloud backup solution with automatic syncing and version control.",
    features: [
      "Automatic data backup",
      "End-to-end encryption",
      "Version history and recovery",
      "Cross-platform compatibility",
      "Scalable storage options",
    ],
    stock: 50,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Business Analytics Dashboard",
    category: "Software Development",
    price: 1499.99,
    image: "/images/products/business-analytics.jpg",
    description: "Customizable analytics dashboard for visualizing business metrics and KPIs.",
    features: [
      "Real-time data visualization",
      "Customizable widgets and reports",
      "Data integration from multiple sources",
      "Export and sharing capabilities",
      "User role management",
    ],
    stock: 12,
    rating: 4.5,
  },
  {
    id: 6,
    name: "Smart Office Kit",
    category: "IT Products & Services",
    price: 2499.99,
    image: "/images/products/smart-office-kit.jpg",
    description: "Complete smart office solution including hardware and software for modern workplaces.",
    features: [
      "Smart lighting and climate control",
      "Meeting room booking system",
      "Visitor management system",
      "Employee access control",
      "Energy usage optimization",
    ],
    stock: 5,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Data Center Cooling System",
    category: "Power Solutions",
    price: 3999.99,
    image: "/images/products/data-center-cooling.jpg",
    description: "Energy-efficient cooling solution designed specifically for data centers and server rooms.",
    features: [
      "Precision temperature control",
      "Humidity management",
      "Energy-efficient operation",
      "Remote monitoring capabilities",
      "Redundant cooling paths",
    ],
    stock: 3,
    rating: 4.8,
  },
  {
    id: 8,
    name: "Managed IT Service Package",
    category: "IT Products & Services",
    price: 599.99,
    image: "/images/products/managed-it-service.jpg",
    description: "Monthly subscription for comprehensive IT management and support for small to medium businesses.",
    features: [
      "24/7 technical support",
      "Network monitoring and management",
      "Security patch management",
      "Backup and disaster recovery",
      "IT consulting and planning",
    ],
    stock: 100,
    rating: 4.7,
  },
  {
    id: 9,
    name: "Network Security Appliance",
    category: "Security Products",
    price: 2499.99,
    image: "/images/products/network-security-appliance.jpg",
    description: "Advanced network security appliance with integrated threat protection and management.",
    features: [
      "Unified threat management",
      "Deep packet inspection",
      "Application control",
      "Web filtering",
      "Centralized management",
    ],
    stock: 10,
    rating: 4.8,
  },
  {
    id: 10,
    name: "UPS System",
    category: "Power Solutions",
    price: 1499.99,
    image: "/images/products/ups-system.jpg",
    description: "Uninterruptible Power Supply system for critical infrastructure and equipment.",
    features: [
      "Pure sine wave output",
      "Automatic voltage regulation",
      "LCD display for monitoring",
      "Hot-swappable batteries",
      "Network management interface",
    ],
    stock: 15,
    rating: 4.7,
  },
  {
    id: 11,
    name: "Wireless Access Point",
    category: "Connectivity & Networking",
    price: 199.99,
    image: "/images/products/wireless-access-point.jpg",
    description: "Enterprise-grade wireless access point with advanced features for high-density environments.",
    features: [
      "WiFi 6 technology",
      "PoE support",
      "Mesh networking capability",
      "Advanced security features",
      "Cloud management",
    ],
    stock: 30,
    rating: 4.6,
  },
  {
    id: 12,
    name: "IT Consulting Service",
    category: "IT Products & Services",
    price: 299.99,
    image: "/images/products/it-consulting.jpg",
    description: "Professional IT consulting services for strategic technology planning and implementation.",
    features: [
      "Technology assessment",
      "Strategic planning",
      "Vendor selection",
      "Implementation support",
      "Ongoing advisory services",
    ],
    stock: 100,
    rating: 4.9,
  },
  {
    id: 13,
    name: "ERP System",
    category: "Software Development",
    price: 4999.99,
    image: "/images/products/erp-system.jpg",
    description: "Comprehensive Enterprise Resource Planning system for business process management.",
    features: [
      "Integrated business modules",
      "Real-time analytics",
      "Customizable workflows",
      "Mobile access",
      "Multi-language support",
    ],
    stock: 5,
    rating: 4.8,
  },
  {
    id: 14,
    name: "E-commerce Platform",
    category: "Web Designing",
    price: 2999.99,
    image: "/images/products/ecommerce-platform.jpg",
    description: "Complete e-commerce solution with advanced features for online retail businesses.",
    features: [
      "Responsive design",
      "Payment gateway integration",
      "Inventory management",
      "Order processing",
      "Customer management",
    ],
    stock: 8,
    rating: 4.7,
  },
  {
    id: 15,
    name: "Endpoint Protection",
    category: "Security Products",
    price: 49.99,
    image: "/images/products/endpoint-protection.jpg",
    description: "Advanced endpoint security solution for protecting devices from threats.",
    features: [
      "Real-time threat detection",
      "Behavioral analysis",
      "Device control",
      "Data loss prevention",
      "Centralized management",
    ],
    stock: 200,
    rating: 4.8,
  },
  {
    id: 16,
    name: "Power Distribution Unit",
    category: "Power Solutions",
    price: 799.99,
    image: "/images/products/power-distribution.jpg",
    description: "Intelligent power distribution unit for data centers and server rooms.",
    features: [
      "Remote power control",
      "Power monitoring",
      "Environmental monitoring",
      "Alarm notifications",
      "Rack mounting",
    ],
    stock: 20,
    rating: 4.6,
  },
  {
    id: 17,
    name: "Network Switch",
    category: "Connectivity & Networking",
    price: 499.99,
    image: "/images/products/network-switch.jpg",
    description: "High-performance network switch for enterprise environments.",
    features: [
      "Layer 3 switching",
      "PoE+ support",
      "VLAN support",
      "Quality of Service",
      "Stacking capability",
    ],
    stock: 25,
    rating: 4.7,
  },
  {
    id: 18,
    name: "Disaster Recovery Solution",
    category: "IT Products & Services",
    price: 1999.99,
    image: "/images/products/disaster-recovery.jpg",
    description: "Comprehensive disaster recovery solution for business continuity.",
    features: [
      "Automated backup",
      "Quick recovery",
      "Data replication",
      "Testing capabilities",
      "24/7 support",
    ],
    stock: 10,
    rating: 4.8,
  },
  {
    id: 19,
    name: "CRM Platform",
    category: "Software Development",
    price: 2999.99,
    image: "/images/products/crm-platform.jpg",
    description: "Customer Relationship Management platform for managing customer interactions.",
    features: [
      "Contact management",
      "Sales pipeline",
      "Marketing automation",
      "Customer service",
      "Analytics and reporting",
    ],
    stock: 15,
    rating: 4.7,
  },
  {
    id: 20,
    name: "Corporate Website",
    category: "Web Designing",
    price: 1999.99,
    image: "/images/products/corporate-website.jpg",
    description: "Professional corporate website design and development service.",
    features: [
      "Custom design",
      "Content management",
      "SEO optimization",
      "Mobile responsive",
      "Analytics integration",
    ],
    stock: 20,
    rating: 4.8,
  },
  {
    id: 21,
    name: "Security Analytics",
    category: "Security Products",
    price: 3999.99,
    image: "/images/products/security-analytics.jpg",
    description: "Advanced security analytics platform for threat detection and response.",
    features: [
      "Real-time monitoring",
      "Threat intelligence",
      "Behavioral analytics",
      "Incident response",
      "Compliance reporting",
    ],
    stock: 5,
    rating: 4.9,
  },
  {
    id: 22,
    name: "Energy Monitoring System",
    category: "Power Solutions",
    price: 1499.99,
    image: "/images/products/energy-monitoring.jpg",
    description: "Comprehensive energy monitoring and management system.",
    features: [
      "Real-time monitoring",
      "Energy analytics",
      "Cost tracking",
      "Alerts and notifications",
      "Reporting tools",
    ],
    stock: 12,
    rating: 4.7,
  },
  {
    id: 23,
    name: "SD-WAN Controller",
    category: "Connectivity & Networking",
    price: 2999.99,
    image: "/images/products/sd-wan-controller.jpg",
    description: "Software-defined WAN controller for network optimization.",
    features: [
      "Centralized management",
      "Traffic optimization",
      "Security integration",
      "Cloud connectivity",
      "Analytics and reporting",
    ],
    stock: 8,
    rating: 4.8,
  },
  {
    id: 24,
    name: "IT Infrastructure Solution",
    category: "IT Products & Services",
    price: 4999.99,
    image: "/images/products/it-infrastructure.jpg",
    description: "Complete IT infrastructure solution for modern businesses.",
    features: [
      "Hardware components",
      "Software solutions",
      "Network setup",
      "Security implementation",
      "Support services",
    ],
    stock: 5,
    rating: 4.9,
  },
  {
    id: 25,
    name: "Mobile App Development",
    category: "Software Development",
    price: 3999.99,
    image: "/images/products/mobile-app.jpg",
    description: "Custom mobile application development service.",
    features: [
      "Native development",
      "Cross-platform support",
      "UI/UX design",
      "Backend integration",
      "App store deployment",
    ],
    stock: 10,
    rating: 4.8,
  },
  {
    id: 26,
    name: "Landing Page Design",
    category: "Web Designing",
    price: 999.99,
    image: "/images/products/landing-page.jpg",
    description: "Professional landing page design and development service.",
    features: [
      "Custom design",
      "Conversion optimization",
      "Mobile responsive",
      "Analytics integration",
      "A/B testing",
    ],
    stock: 25,
    rating: 4.7,
  },
  {
    id: 27,
    name: "Threat Intelligence Platform",
    category: "Security Products",
    price: 2999.99,
    image: "/images/products/threat-intelligence.jpg",
    description: "Advanced threat intelligence platform for proactive security.",
    features: [
      "Real-time threat feeds",
      "Vulnerability assessment",
      "Risk analysis",
      "Incident response",
      "Compliance monitoring",
    ],
    stock: 8,
    rating: 4.8,
  },
  {
    id: 28,
    name: "Backup Power System",
    category: "Power Solutions",
    price: 1999.99,
    image: "/images/products/backup-power.jpg",
    description: "Reliable backup power system for critical operations.",
    features: [
      "Automatic switching",
      "Battery backup",
      "Power monitoring",
      "Remote management",
      "Scalable capacity",
    ],
    stock: 15,
    rating: 4.7,
  },
  {
    id: 29,
    name: "Network Monitoring Tool",
    category: "Connectivity & Networking",
    price: 1499.99,
    image: "/images/products/network-monitoring.jpg",
    description: "Comprehensive network monitoring and management solution.",
    features: [
      "Real-time monitoring",
      "Performance analysis",
      "Alert system",
      "Reporting tools",
      "Device management",
    ],
    stock: 20,
    rating: 4.8,
  },
  {
    id: 30,
    name: "Web Application Development",
    category: "Software Development",
    price: 3499.99,
    image: "/images/products/web-application.jpg",
    description: "Custom web application development service.",
    features: [
      "Custom development",
      "Database integration",
      "API development",
      "Security implementation",
      "Cloud deployment",
    ],
    stock: 12,
    rating: 4.7,
  },
  {
    id: 31,
    name: "Web Redesign Service",
    category: "Web Designing",
    price: 1499.99,
    image: "/images/products/web-redesign.jpg",
    description: "Professional website redesign service for modern businesses.",
    features: [
      "Modern design",
      "Content optimization",
      "SEO improvement",
      "Performance optimization",
      "Mobile responsiveness",
    ],
    stock: 18,
    rating: 4.8,
  },
  {
    id: 32,
    name: "Secure Access Gateway",
    category: "Security Products",
    price: 1999.99,
    image: "/images/products/secure-access-gateway.jpg",
    description: "Secure access gateway for remote and mobile users.",
    features: [
      "VPN support",
      "Multi-factor authentication",
      "Access control",
      "Traffic inspection",
      "Policy enforcement",
    ],
    stock: 15,
    rating: 4.7,
  },
  {
    id: 33,
    name: "UI Design Service",
    category: "Web Designing",
    price: 999.99,
    image: "/images/products/ui-design.jpg",
    description: "Professional UI design service for digital products.",
    features: [
      "User research",
      "Wireframing",
      "Visual design",
      "Prototyping",
      "Design system",
    ],
    stock: 30,
    rating: 4.8,
  },
  {
    id: 34,
    name: "Custom Software Development",
    category: "Software Development",
    price: 4999.99,
    image: "/images/products/custom-software.jpg",
    description: "Custom software development service for unique business needs.",
    features: [
      "Requirements analysis",
      "Custom development",
      "Quality assurance",
      "Documentation",
      "Support services",
    ],
    stock: 8,
    rating: 4.9,
  },
  {
    id: 35,
    name: "VPN Gateway",
    category: "Connectivity & Networking",
    price: 799.99,
    image: "/images/products/vpn-gateway.jpg",
    description: "Secure VPN gateway for remote access and site-to-site connectivity.",
    features: [
      "High-performance encryption",
      "Multiple VPN protocols",
      "Load balancing",
      "Failover support",
      "Centralized management",
    ],
    stock: 25,
    rating: 4.7,
  },
  {
    id: 36,
    name: "Responsive Design Service",
    category: "Web Designing",
    price: 1299.99,
    image: "/images/products/responsive-design.jpg",
    description: "Professional responsive web design service for all devices.",
    features: [
      "Mobile-first approach",
      "Cross-device testing",
      "Performance optimization",
      "User experience",
      "SEO friendly",
    ],
    stock: 20,
    rating: 4.8,
  },
]

export const services = [
  {
    id: 1,
    title: "Custom Software Development",
    category: "Software Development",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Tailored software solutions designed to meet your specific business requirements.",
    description:
      "Our expert development team creates custom software solutions that address your unique business challenges. From enterprise applications to specialized tools, we deliver high-quality, scalable software that drives efficiency and growth.",
    process: [
      "Requirements gathering and analysis",
      "Solution architecture and design",
      "Agile development and testing",
      "Deployment and integration",
      "Ongoing support and maintenance",
    ],
    technologies: ["React", "Node.js", "Python", "Java", "AWS", "Azure", ".NET", "MongoDB", "PostgreSQL"],
    caseStudies: [
      {
        title: "Enterprise Resource Planning System",
        client: "Manufacturing Company",
        outcome: "40% increase in operational efficiency",
      },
      {
        title: "Customer Relationship Management Tool",
        client: "Financial Services Provider",
        outcome: "65% improvement in customer retention",
      },
    ],
  },
  {
    id: 2,
    title: "Web Design & Development",
    category: "Web Designing",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Stunning, responsive websites with modern UI/UX that captivate your audience.",
    description:
      "We create visually appealing, user-friendly websites that represent your brand and engage your audience. Our web solutions are responsive, accessible, and optimized for performance across all devices and platforms.",
    process: [
      "Discovery and strategy planning",
      "Wireframing and prototyping",
      "Visual design and branding",
      "Frontend and backend development",
      "Testing, launch, and post-launch support",
    ],
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Next.js",
      "WordPress",
      "Shopify",
      "Tailwind CSS",
      "GraphQL",
    ],
    caseStudies: [
      {
        title: "E-commerce Platform Redesign",
        client: "Retail Chain",
        outcome: "35% increase in conversion rate",
      },
      {
        title: "Corporate Website Overhaul",
        client: "Legal Firm",
        outcome: "120% increase in lead generation",
      },
    ],
  },
  {
    id: 3,
    title: "Power Management Solutions",
    category: "Power Solutions",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Reliable power management systems to keep your infrastructure running efficiently.",
    description:
      "Our power management solutions help businesses optimize energy usage, reduce costs, and ensure uninterrupted operations. We provide comprehensive services from assessment to implementation and ongoing monitoring.",
    process: [
      "Energy audit and assessment",
      "Solution design and planning",
      "Equipment procurement and installation",
      "System integration and testing",
      "Monitoring and maintenance",
    ],
    technologies: [
      "Smart Grid Technology",
      "Energy Management Systems",
      "UPS Systems",
      "Power Distribution Units",
      "Renewable Energy Integration",
    ],
    caseStudies: [
      {
        title: "Smart Grid Power Management",
        client: "Commercial Building Complex",
        outcome: "25% reduction in power consumption",
      },
      {
        title: "Data Center Power Optimization",
        client: "Cloud Service Provider",
        outcome: "30% improvement in energy efficiency",
      },
    ],
  },
  {
    id: 4,
    title: "Cybersecurity Services",
    category: "Security Products",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Comprehensive security solutions to protect your digital assets from threats.",
    description:
      "Our cybersecurity services provide robust protection for your digital infrastructure, data, and applications. We implement multi-layered security strategies to defend against evolving threats and ensure business continuity.",
    process: [
      "Security assessment and vulnerability scanning",
      "Security architecture design",
      "Implementation of security controls",
      "Security monitoring and incident response",
      "Security awareness training",
    ],
    technologies: [
      "Firewall Systems",
      "Intrusion Detection",
      "Endpoint Protection",
      "Data Encryption",
      "Identity Management",
      "Security Information and Event Management (SIEM)",
    ],
    caseStudies: [
      {
        title: "Secure Banking Infrastructure",
        client: "Regional Bank",
        outcome: "Zero security breaches since implementation",
      },
      {
        title: "Healthcare Data Protection",
        client: "Medical Center",
        outcome: "Achieved HIPAA compliance with enhanced security",
      },
    ],
  },
  {
    id: 5,
    title: "Network Infrastructure",
    category: "Connectivity & Networking",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Robust networking solutions that ensure seamless connectivity across your organization.",
    description:
      "We design, implement, and manage network infrastructure that provides reliable, high-performance connectivity for your business. Our solutions scale with your needs and incorporate the latest technologies for optimal performance.",
    process: [
      "Network assessment and planning",
      "Architecture design",
      "Equipment selection and procurement",
      "Implementation and configuration",
      "Network monitoring and management",
    ],
    technologies: [
      "Cisco Systems",
      "SD-WAN",
      "Network Virtualization",
      "Cloud Networking",
      "Wireless Solutions",
      "VPN Technologies",
    ],
    caseStudies: [
      {
        title: "Corporate Network Infrastructure",
        client: "Multinational Corporation",
        outcome: "99.99% network uptime across 20+ locations",
      },
      {
        title: "Campus-wide WiFi Deployment",
        client: "University",
        outcome: "Seamless connectivity for 15,000+ simultaneous users",
      },
    ],
  },
  {
    id: 6,
    title: "IT Consulting & Support",
    category: "IT Products & Services",
    image: "/placeholder.svg?height=600&width=800",
    shortDescription: "Expert IT consulting and support services for your business technology needs.",
    description:
      "Our IT consulting and support services provide strategic guidance and technical expertise to help you leverage technology for business success. We offer proactive support, problem resolution, and strategic planning to optimize your IT investments.",
    process: [
      "IT assessment and discovery",
      "Strategic planning and roadmap development",
      "Solution recommendation and implementation",
      "Ongoing support and maintenance",
      "Regular review and optimization",
    ],
    technologies: [
      "Help Desk Systems",
      "Remote Monitoring",
      "IT Service Management",
      "Cloud Migration",
      "Digital Transformation",
    ],
    caseStudies: [
      {
        title: "IT Infrastructure Modernization",
        client: "Accounting Firm",
        outcome: "50% reduction in IT-related downtime",
      },
      {
        title: "Cloud Migration Strategy",
        client: "Insurance Company",
        outcome: "35% reduction in IT operational costs",
      },
    ],
  },
]

export const projects = [
  {
    id: 1,
    title: "Enterprise Resource Planning System",
    category: "Software Development",
    client: "Global Manufacturing Corporation",
    duration: "18 months",
    year: 2022,
    location: "Chicago, IL",
    description:
      "Developed and implemented a comprehensive ERP solution for a manufacturing company with operations in 12 countries. The system integrated production, inventory, sales, and financial data into a unified platform, providing real-time insights and streamlining operations.",
    challenge:
      "The client was struggling with siloed data across multiple legacy systems, leading to inefficiencies, data inconsistencies, and delayed decision-making. They needed a unified solution that could handle complex manufacturing processes while providing real-time visibility across the organization.",
    solution:
      "We designed a custom ERP system tailored to the client's specific manufacturing processes. The solution included modules for production planning, inventory management, supply chain, quality control, sales, and financial management. We implemented a phased approach to minimize disruption and ensure successful adoption.",
    results: [
      "40% increase in operational efficiency",
      "25% reduction in inventory costs",
      "60% faster reporting and analytics",
      "Seamless integration across 12 international locations",
      "ROI achieved within 14 months of full implementation",
    ],
    technologies: ["React", "Node.js", "MongoDB", "Docker", "Kubernetes", "Azure Cloud"],
    image: "/images/projects/erp-system.jpg",
    gallery: [
      "/images/projects/erp-system-1.jpg",
      "/images/projects/erp-system-2.jpg",
      "/images/projects/erp-system-3.jpg",
    ],
    testimonial: {
      quote: "The ERP system has transformed our operations and given us unprecedented visibility into our business processes.",
      author: "John Smith",
      position: "CIO",
      company: "Global Manufacturing Corporation",
    },
  },
  {
    id: 2,
    title: "E-commerce Platform Redesign",
    category: "Web Designing",
    client: "Fashion Retail Brand",
    duration: "6 months",
    year: 2023,
    location: "New York, NY",
    description:
      "Complete redesign of an e-commerce platform for a leading fashion retail brand, focusing on user experience, mobile responsiveness, and conversion optimization.",
    challenge:
      "The client's existing e-commerce platform had poor mobile performance, high cart abandonment rates, and an outdated design that didn't reflect their brand identity.",
    solution:
      "We redesigned the entire platform with a mobile-first approach, implemented a new design system, and optimized the checkout process. We also integrated advanced product filtering and search capabilities.",
    results: [
      "35% increase in conversion rate",
      "50% improvement in mobile engagement",
      "40% reduction in cart abandonment",
      "25% increase in average order value",
      "Improved customer satisfaction scores",
    ],
    technologies: ["Next.js", "Tailwind CSS", "Shopify", "Stripe", "Algolia Search"],
    image: "/images/projects/ecommerce-redesign.jpg",
    gallery: [
      "/images/projects/ecommerce-1.jpg",
      "/images/projects/ecommerce-2.jpg",
      "/images/projects/ecommerce-3.jpg",
    ],
    testimonial: {
      quote: "The new platform has significantly improved our online sales and customer experience.",
      author: "Sarah Johnson",
      position: "E-commerce Director",
      company: "Fashion Retail Brand",
    },
  },
  {
    id: 3,
    title: "Secure Banking Infrastructure",
    category: "Security Products",
    client: "Regional Banking Network",
    duration: "12 months",
    year: 2022,
    location: "Boston, MA",
    description:
      "Designed and implemented a comprehensive security infrastructure for a regional banking network with 50+ branches. The solution included advanced encryption, multi-factor authentication, and real-time threat monitoring.",
    challenge:
      "The client faced increasing cybersecurity threats and needed to strengthen their security posture while complying with stringent financial regulations. They required a solution that provided robust protection without impacting system performance or user experience.",
    solution:
      "We developed a multi-layered security architecture that included network segmentation, advanced firewall protection, encryption for data at rest and in transit, and a comprehensive identity and access management system. We also implemented a security operations center for 24/7 monitoring and incident response.",
    results: [
      "Zero security breaches since implementation",
      "100% compliance with banking regulations",
      "90% reduction in security incidents",
      "Streamlined authentication process for employees",
      "Enhanced customer trust through improved security measures",
    ],
    technologies: [
      "Cisco Security",
      "Palo Alto Networks",
      "Okta",
      "Splunk",
      "Encryption Technologies",
      "Biometric Authentication",
    ],
    image: "/images/projects/banking-security.jpg",
    gallery: [
      "/images/projects/banking-1.jpg",
      "/images/projects/banking-2.jpg",
      "/images/projects/banking-3.jpg",
    ],
    testimonial: {
      quote: "The security infrastructure has given us peace of mind and helped us maintain our customers' trust.",
      author: "Michael Brown",
      position: "CISO",
      company: "Regional Banking Network",
    },
  },
  {
    id: 4,
    title: "Smart Grid Power Management",
    category: "Power Solutions",
    client: "Commercial Real Estate Developer",
    duration: "15 months",
    year: 2023,
    location: "San Francisco, CA",
    description:
      "Developed and implemented a smart grid power management system for a large commercial real estate portfolio, integrating renewable energy sources and advanced monitoring capabilities.",
    challenge:
      "The client needed to reduce energy costs and carbon footprint while maintaining reliable power supply across multiple properties. They required a solution that could integrate with existing infrastructure and provide real-time monitoring.",
    solution:
      "We designed a comprehensive smart grid solution that included IoT sensors, energy management systems, solar integration, and battery storage. The system uses AI/ML algorithms to optimize energy distribution and predict maintenance needs.",
    results: [
      "25% reduction in overall power consumption",
      "40% decrease in energy costs",
      "30% reduction in carbon emissions",
      "Real-time visibility into energy usage patterns",
      "Enhanced resilience against power outages",
    ],
    technologies: [
      "IoT Sensors",
      "Energy Management Systems",
      "Solar Integration",
      "Battery Storage",
      "AI/ML Algorithms",
      "Cloud Analytics",
    ],
    image: "/images/projects/smart-grid.jpg",
    gallery: [
      "/images/projects/smart-grid-1.jpg",
      "/images/projects/smart-grid-2.jpg",
      "/images/projects/smart-grid-3.jpg",
    ],
    testimonial: {
      quote: "The smart grid system has revolutionized our energy management and significantly reduced our operational costs.",
      author: "David Wilson",
      position: "Facilities Director",
      company: "Commercial Real Estate Developer",
    },
  },
  {
    id: 5,
    title: "Corporate Network Infrastructure",
    category: "Connectivity & Networking",
    client: "Global Consulting Firm",
    duration: "8 months",
    year: 2022,
    location: "London, UK",
    description:
      "Designed and implemented a scalable network infrastructure for a multinational consulting firm with 20+ offices worldwide. The solution provided secure, high-performance connectivity while supporting remote work capabilities.",
    challenge:
      "The client's existing network was struggling to support their growing global operations and increasing reliance on cloud applications. They needed a solution that could provide consistent performance across all locations while supporting their hybrid work model.",
    solution:
      "We implemented a software-defined wide area network (SD-WAN) architecture that optimized traffic routing across their global offices. The solution included redundant internet connections, quality of service controls, and integrated security features. We also deployed a global VPN solution to support remote workers with secure access to corporate resources.",
    results: [
      "99.99% network uptime across all locations",
      "60% improvement in application performance",
      "Seamless support for 5,000+ remote workers",
      "Simplified network management through centralized controls",
      "Reduced network operating costs by 35%",
    ],
    technologies: [
      "Cisco SD-WAN",
      "Meraki",
      "Azure Virtual WAN",
      "Zero Trust Security",
      "Cloud Connectivity",
      "Global VPN",
    ],
    image: "/images/projects/network-infrastructure.jpg",
    gallery: [
      "/images/projects/network-1.jpg",
      "/images/projects/network-2.jpg",
      "/images/projects/network-3.jpg",
    ],
    testimonial: {
      quote: "The new network infrastructure has transformed our global operations and enabled seamless remote work.",
      author: "Emma Thompson",
      position: "IT Director",
      company: "Global Consulting Firm",
    },
  },
  {
    id: 6,
    title: "Healthcare IT System Integration",
    category: "IT Products & Services",
    client: "Regional Healthcare Provider",
    duration: "10 months",
    year: 2023,
    location: "Toronto, Canada",
    description:
      "Integrated various healthcare IT systems to create a unified platform for patient data management and analytics, improving care coordination and operational efficiency.",
    challenge:
      "The healthcare provider was using multiple disconnected systems for patient records, scheduling, billing, and analytics. This led to inefficiencies, data inconsistencies, and challenges in providing coordinated care.",
    solution:
      "We developed an integrated healthcare IT platform that connected all existing systems through standardized APIs and a central data warehouse. The solution included a unified patient portal, clinical decision support tools, and advanced analytics capabilities.",
    results: [
      "Unified patient records across 12 facilities",
      "45% reduction in administrative data entry",
      "70% faster access to complete patient information",
      "Improved care coordination and reduced duplicate testing",
      "Full compliance with HIPAA and other healthcare regulations",
    ],
    technologies: [
      "HL7 FHIR",
      "Interoperability APIs",
      "Healthcare Data Warehouse",
      "HIPAA-Compliant Cloud",
      "Clinical Analytics",
      "Secure Messaging",
    ],
    image: "/images/projects/healthcare-it.jpg",
    gallery: [
      "/images/projects/healthcare-1.jpg",
      "/images/projects/healthcare-2.jpg",
      "/images/projects/healthcare-3.jpg",
    ],
    testimonial: {
      quote: "The integrated system has significantly improved our ability to provide coordinated care and reduced administrative burden.",
      author: "Dr. Lisa Chen",
      position: "Chief Medical Information Officer",
      company: "Regional Healthcare Provider",
    },
  },
]

export const teamMembers = [
  {
    id: 1,
    name: "Eng. Furaha Mndeme",
    role: "Founder & CEO",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Mndeme founded QuardCubeLabs in 2008 with a vision to transform how businesses leverage technology. With a Ph.D. in Computer Science and over 25 years of industry experience, he leads the company's strategic direction and innovation initiatives.",
    expertise: ["Strategic Leadership", "Technology Innovation", "Enterprise Architecture", "Digital Transformation"],
    education: "M.S. in Computer Engineering, MIT",
    socialMedia: {
      whatsapp: "https://wa.me/+255652540496",
      instagram: "https://instagram.com/framan_reubinstein",
      twitter: "https://twitter.com/framan007",
    },
  },
  {
    id: 2,
    name: "Fadhili Mndeme",
    role: "Chief Technology Officer",
    image: "/placeholder.svg?height=400&width=400",
    bio: "Fadhili oversees all technical aspects of the company, from software development to infrastructure solutions. Her background in both software engineering and systems architecture enables her to bridge complex technical concepts with practical business applications.",
    expertise: ["Software Architecture", "Cloud Computing", "AI & Machine Learning", "Cybersecurity"],
    education: "M.S. in Computer Engineering, Stanford University",
    socialMedia: {
      whatsapp: "https://wa.me/1234567891",
      instagram: "https://instagram.com/sarahchen",
      twitter: "https://twitter.com/sarahchen",
    },
  },
  {
    id: 3,
    name: "Dr. Hossiana Walter",
    role: "Operations Manager",
    image: "/hosie.jpeg",
    bio: "Hossiana leads our security practice, ensuring that all solutions meet the highest standards of security and compliance. With a background in cybersecurity and risk management, he has helped numerous organizations protect their critical assets from evolving threats.",
    expertise: ["Cybersecurity Strategy", "Risk Management", "Compliance", "Security Architecture"],
    education: "M.S. in Information Security, Carnegie Mellon University",
    socialMedia: {
      whatsapp: "https://wa.me/+255679933463",
      instagram: "https://instagram.com/hossianawalter",
      twitter: "https://twitter.com/hossianawalter",
    },
  },
]

export const companyHistory = [
  {
    year: 2008,
    title: "Foundation",
    description:
      "QuardCubeLabs was founded by Dr. James Wilson with a vision to provide innovative technology solutions for businesses of all sizes.",
  },
  {
    year: 2010,
    title: "First Major Client",
    description:
      "Secured our first enterprise client, a regional bank that needed a comprehensive security infrastructure overhaul.",
  },
  {
    year: 2012,
    title: "Expansion of Services",
    description:
      "Expanded our service offerings to include software development and web design, broadening our ability to serve clients' diverse needs.",
  },
  {
    year: 2014,
    title: "New Headquarters",
    description:
      "Moved to our current headquarters, a state-of-the-art facility designed to foster collaboration and innovation.",
  },
  {
    year: 2016,
    title: "International Expansion",
    description: "Opened our first international office in London, UK, extending our reach to European markets.",
  },
  {
    year: 2018,
    title: "Technology Innovation Award",
    description:
      "Received the prestigious Technology Innovation Award for our work in developing secure, scalable enterprise solutions.",
  },
  {
    year: 2020,
    title: "Remote Work Solutions",
    description:
      "Developed specialized solutions to help businesses transition to remote work environments during the global pandemic.",
  },
  {
    year: 2022,
    title: "AI & Machine Learning Practice",
    description:
      "Established a dedicated AI and Machine Learning practice to help clients leverage these transformative technologies.",
  },
  {
    year: 2023,
    title: "Sustainability Initiative",
    description:
      "Launched our sustainability initiative, focusing on developing technology solutions that reduce environmental impact.",
  },
]

export const faqs = [
  {
    question: "What industries does QuardCubeLabs serve?",
    answer:
      "We serve a wide range of industries including finance, healthcare, manufacturing, retail, education, and professional services. Our solutions are adaptable to the specific needs and regulatory requirements of each industry.",
  },
  {
    question: "How does your software development process work?",
    answer:
      "Our software development process follows an agile methodology, with regular client touchpoints and iterative development cycles. We begin with a thorough discovery phase to understand your requirements, followed by design, development, testing, and deployment phases. Throughout the process, we maintain transparent communication and adapt to changing needs.",
  },
  {
    question: "What security certifications does QuardCubeLabs hold?",
    answer:
      "QuardCubeLabs maintains several industry-standard security certifications including ISO 27001, SOC 2 Type II, and PCI DSS. Our security professionals also hold individual certifications such as CISSP, CEH, and CISM. We regularly undergo third-party security audits to ensure our practices meet the highest standards.",
  },
  {
    question: "Can you work with our existing IT infrastructure?",
    answer:
      "Yes, we specialize in integrating with existing IT infrastructures. Our solutions are designed to complement and enhance your current systems, minimizing disruption while maximizing value. We conduct thorough assessments of your existing environment before recommending integration approaches.",
  },
  {
    question: "What support options do you offer after project completion?",
    answer:
      "We offer various support options including 24/7 technical support, scheduled maintenance, regular updates, and ongoing optimization. Our support packages can be tailored to your specific needs, whether you require basic assistance or comprehensive managed services. We also provide training for your team to ensure they can effectively use the implemented solutions.",
  },
  {
    question: "How do you handle data privacy and compliance?",
    answer:
      "We take data privacy and compliance very seriously. Our solutions are designed with privacy by design principles and comply with relevant regulations such as GDPR, HIPAA, and CCPA. We implement robust data protection measures, maintain detailed documentation, and provide transparency about data handling practices. Our team stays current with evolving regulations to ensure ongoing compliance.",
  },
  {
    question: "What is your approach to project management?",
    answer:
      "Our project management approach combines agile methodologies with clear communication and accountability. Each project is assigned a dedicated project manager who serves as your primary point of contact. We use collaborative tools for transparency, conduct regular status meetings, and provide detailed progress reports. Our goal is to deliver projects on time, within budget, and to your complete satisfaction.",
  },
  {
    question: "Can you scale solutions as our business grows?",
    answer:
      "Absolutely. Scalability is a core consideration in all our solutions. We design systems with future growth in mind, using modular architectures and scalable technologies. Our cloud-based solutions can easily adapt to increasing demands, and our on-premises implementations include capacity planning for future expansion. We also provide roadmap planning to help you anticipate and prepare for technology needs as your business evolves.",
  },
]

export const categories = [
  "All",
  "Software Development",
  "Web Designing",
  "Security Products",
  "Power Solutions",
  "Connectivity & Networking",
  "IT Products & Services",
]

export const cartItems = []
